### PR TITLE
Styling, background colour

### PR DESCRIPTION
**Pull request by wilkgr76**
Hire me? &lt;g&gt;

### CODE REVIEW

**Comment by wilkgr76** [comment]
FWIW, that was intended as a joke

**Comment by wilkgr76** [comment]
If you want to see how it looks now: https://wilkgr76.github.io/totallynotashadyweb.site/

**Comment by benrob0329** [comment]
I was thinking a "hacker" style green on black theme, to enhance the shadyness :stuck_out_tongue:

**Comment by wilkgr76** [comment]
aye aye capt'n

**Comment by wilkgr76** [comment]
@benrob0329 Changed. Could you check? (Link: https://wilkgr76.github.io/totallynotashadyweb.site/)

**Comment by benrob0329** [comment]
Better, i'd love it if we could get a super terminally look to it but that's probably hard to do..

I'd make the background a little darker, maybe have the highlight more centered so it makes the screen look rounded :P

**Comment by wilkgr76** [comment]
Now?

**Comment by wilkgr76** [comment]
That's all I'm doing with this damn background

**Comment by benrob0329** [comment]
That should be more of what I was thinking, but it doesn't seem to change on your instance...

**Comment by wilkgr76** [comment]
Perhaps the cache. If you hit Ctrl Shift R, that should reload without
cache.

**Comment by benrob0329** [comment]
There, its more subtle, and closer to what I was thinking

**Pull request merged**
